name: "Deploy on comment"

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    outputs:
      triggered: ${{ steps.step1.outputs.triggered }}
    steps:
      - uses: shanegenschaw/pull-request-comment-trigger@v2.1.0
        id: check
        with:
          trigger: "deploy:staging"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: "echo Found it!"
        if: steps.check.outputs.triggered == 'true'

  merge_to_test:
    name: Merge to test branch

    needs:
      - trigger

    if: needs.trigger.outputs.triggered == 'true'

    runs-on: ubuntu-latest

    steps:
      - name: Merge
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: test
          github_token: ${{ secrets.GITHUB_TOKEN }}
