name: Deploy test

on: 
  - workflow_call

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  deploy_dev:
    name: Deploy

    needs:
      - build_and_test

    runs-on: ubuntu-latest
    concurrency: dev

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: "Deploy development"
        run: |
          echo "Prettend deploy to DEVELOPMENT"

  deploy_staging:
    name: Deploy

    needs: 
      - build_and_test

    runs-on: ubuntu-latest
    concurrency: staging

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: "Deploy staging"
        run: |
          echo "Prettend deploy to STAGING"
