name: Merge branch to test on labeled

on:
  pull_request:
    types:
      - labeled
  pull_request_review:
    types:
      - submitted

jobs:
  merge_branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Merge PR to test by label
        uses: devmasx/merge-branch@master
        with:
          label_name: merge to test branch
          target_branch: test
          github_token: ${{ secrets.GITHUB_TOKEN }}
