name: Merge to test

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shanegenschaw/pull-request-comment-trigger@v2.1.0
        id: check
        with:
          trigger: '#deploy:test'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'

# jobs:
#   checkReviews:
#     runs-on: ubuntu-latest
#     outputs:
#       reviews: ${{ steps.reviews.outputs.state }}
#     steps:
#       - id: reviews
#         env:
#           pr: ${{ github.event.number }}
#           GH_TOKEN: ${{}}
#         run: |
#           state=$(gh pr view "$pr" \
#               --repo "$GITHUB_REPOSITORY" 
#               --json reviewDecision \
#               --jq '.reviewDecision')
#           echo "state=$state" >> "$GITHUB_OUTPUT"
#
#   merge_to_test:
#     runs-on: ubuntu-latest
#
#     needs:
#       - checkReviews
#       - build_and_test
#
#     if: needs.checkReviews.event.review.state == 'APPROVED'
#
#     steps:
#       - uses: shanegenschaw/pull-request-comment-trigger@v2.1.0
#         id: check
#         with:
#           trigger: '/deploy:test'
#           reaction: rocket
#         env:
#           GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
#       - run: 'echo found it!'
#         if: steps.check.outputs.triggered == 'true'
#
#       - name: Opening pull request
#         if: failure() && steps.merge_to_test.conclusion == 'failure'
#         id: open_merge_conflict_pull_request
#         uses: tretuna/sync-branches@1.4.0
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           FROM_BRANCH: ${{ github.head_ref }}
#           TO_BRANCH: "test"
