name: Reset merge branch to test label
on:
  pull_request:
    types:
      - synchronize
      - reopened

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            merge to test branch
