on:
  pull_request:
    types: [opened]
  push:
    branches: [main test]
jobs:
  salus_scan_job:
    runs-on: ubuntu-latest
    name: Salus Security Scan
    steps:
      - uses: actions/checkout@v1
      - name: Salus Scan
        id: salus_scan
        uses: federacy/scan-action@0.1.5
        with:
          enforced_scanners: "none"
          active_scanners: "\n  - Brakeman\n  - PatternSearch\n  - RepoNotEmpty\n  - Semgrep\n  - Trufflehog"
